version: '3'

services:
  client:
    build:
      dockerfile: ./Dockerfile.prod
    ports:
      - 80:3000
    environment:
      NODE_ENV: production
    volumes:
      - ./var/log/nginx:/var/log/nginx

  server:
    build:
      dockerfile: ./Dockerfile.prod
    environment:
      NODE_ENV: production
    volumes:
      - ./express-server:/usr/src/backend-app
      - node_modules_b:/usr/src/backend-app/node_modules
