version: '3'

services:
  client:
    build:
      context: ./react-client
    ports:
      - 3000:3000
    depends_on: 
      - server
    networks:
      - frontend

  server:
    build:
      context: ./express-server
    ports:
      - "127.0.0.1:5000:5000"
    depends_on: 
      - mongo
    networks:
      - frontend
      - backend

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    command: --quiet
    networks:
      - backend


volumes: 
  node_modules:
  node_modules_b:
  data:
    
networks:
  frontend:
  backend:

  


    

    