version: '3'
services:
  client:
    build:
      dockerfile: ./Dockerfile.prod
    ports:
      - "127.0.0.1:80:127.0.0.1:8080"
    environment:
      NODE_ENV: production
    volumes:
      - ./var/log/nginx:/var/log/nginx

  server:
    build:
      dockerfile: ./Dockerfile.prod
    environment:
      NODE_ENV: production
    volumes:
      - ./express-server:/usr/src/backend-app
      - node_modules_b:/usr/src/backend-app/node_modules
