version: '3'

services:
  client:
    build:
      context: ./react-client
    depends_on: 
      - server
    networks:
      - frontend

  server:
    build:
      context: ./express-server
    ports:
      - 5000:5000
    depends_on: 
      - mongo
    networks:
      - frontend
      - backend

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
    command: --quiet
    networks:
      - backend


volumes:
  nginx:
  node_modules:
  node_modules_b:
  data:
    
networks:
  frontend:
  backend:

  


    

    